"""
Generate the frontend data module from the model outputs.

Previously this was an ad-hoc snippet, which meant the committed players.js
could silently drift out of sync with the CSV it came from. Now it is a script
you can re-run, and it fails loudly if its input is missing.

It also answers a question the frontend could not previously answer: *does this
player actually play in the Premier League?* The index scores all 256 Euro 2024
players regardless of league, which is correct — it needs no labels — but it
meant Lamine Yamal and Cristiano Ronaldo appeared on a page a visitor would
reasonably assume was about England. Joining the actuals gives every player a
club where we have one, and an `inPL` flag the UI can filter on.

Run:
    python backend/models/index_score.py       # produces the index CSV
    python backend/data/fetch_actuals.py       # optional, adds club + inPL
    python backend/models/export_frontend.py

Writes frontend/src/data/players.js
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from common import ACTUALS_CSV, MODELS_DIR, OUTPUT_DIR, name_keys

INDEX_CSV = OUTPUT_DIR / "euro_impact_index.csv"
FRONTEND_DATA = MODELS_DIR.parent.parent / "frontend" / "src" / "data" / "players.js"


def build_club_lookup(actuals: pd.DataFrame) -> dict[str, dict]:
    """
    Map every name variant of every Premier League player to their club record.

    Sorted by minutes descending so that when two players share a surname key,
    the established first-teamer wins over an academy namesake.
    """
    actuals = actuals.sort_values("epl_minutes", ascending=False)
    lookup: dict[str, dict] = {}

    for row in actuals.itertuples(index=False):
        record = {
            "club": row.club,
            "eplMinutes": int(row.epl_minutes),
            "eplXgi90": round(float(row.epl_xgi_90), 3),
        }
        variants = name_keys(row.player_name) | name_keys(getattr(row, "web_name", ""))
        for key in variants:
            lookup.setdefault(key, record)

    return lookup


def match_club(player_name: str, lookup: dict[str, dict]) -> dict | None:
    # Most specific key first: full name beats first+last beats bare surname.
    for key in sorted(name_keys(player_name), key=len, reverse=True):
        if key in lookup:
            return lookup[key]
    return None


def main() -> None:
    if not INDEX_CSV.exists():
        raise SystemExit(
            f"Missing {INDEX_CSV}\nRun `python backend/models/index_score.py` first."
        )

    index = pd.read_csv(INDEX_CSV)
    print(f"  read {len(index)} ranked players from {INDEX_CSV.name}")

    lookup: dict[str, dict] = {}
    if ACTUALS_CSV.exists():
        actuals = pd.read_csv(ACTUALS_CSV)
        n_clubs = actuals["club"].nunique()
        lookup = build_club_lookup(actuals)
        print(f"  read {len(actuals)} Premier League records across {n_clubs} clubs")
        if n_clubs != 20:
            print(f"  WARNING: {n_clubs} clubs, not 20 — re-run fetch_actuals.py "
                  "without --live")
    else:
        print(f"  NOTE: {ACTUALS_CSV.name} not found — club and inPL will be blank.")
        print("  Run `python backend/data/fetch_actuals.py` to enrich the export.")

    players = []
    for row in index.itertuples(index=False):
        club_record = match_club(row.player_name, lookup) if lookup else None
        players.append(
            {
                "name": str(row.player_name).strip(),
                "nation": str(row.team_name).strip(),
                "role": str(row.role).strip(),
                "age": int(float(row.age)),
                "minutes": int(float(row.minutes)),
                "xgi90": round(float(row.npxg_xag_90), 3),
                "score": round(float(row.index_score), 4),
                "rating": round(float(row.rating_5pt), 2),
                "rankInRole": int(row.rank_in_role),
                "gkAvailabilityOnly": str(row.role).strip() == "GK",
                "club": club_record["club"] if club_record else None,
                "inPL": bool(club_record),
                "eplXgi90": club_record["eplXgi90"] if club_record else None,
            }
        )

    players.sort(key=lambda p: -p["score"])
    for i, p in enumerate(players):
        p["rank"] = i + 1

    FRONTEND_DATA.parent.mkdir(parents=True, exist_ok=True)
    with FRONTEND_DATA.open("w", encoding="utf-8") as fh:
        fh.write("// Generated by backend/models/export_frontend.py — do not edit by hand.\n")
        fh.write("export const PLAYERS = ")
        json.dump(players, fh, ensure_ascii=False, indent=2)
        fh.write(";\n")

    n_pl = sum(1 for p in players if p["inPL"])
    by_role: dict[str, int] = {}
    for p in players:
        by_role[p["role"]] = by_role.get(p["role"], 0) + 1

    print(f"\n  wrote {FRONTEND_DATA}")
    print(f"  {len(players)} players  |  by role: {by_role}")
    print(f"  {n_pl} in the Premier League, {len(players) - n_pl} elsewhere")

    print("\n  top 5 overall:")
    for p in players[:5]:
        where = p["club"] or f"{p['nation']} (not PL)"
        print(f"    {p['rank']:>3}. {p['name']:28s} {p['role']}  "
              f"{p['rating']:.1f}  {p['minutes']:>4}'  {where}")


if __name__ == "__main__":
    main()
